# Cấu hình chung cho tất cả các hàm
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Cấu hình lịch chạy cụ thể cho hàm 'checkForNewChapters'
[functions.checkForNewChapters]
  schedule = "0 * * * *"

# Plugin để tự động cài đặt các dependencies của hàm
[[plugins]]
  package = "@netlify/plugin-functions-install-core"
