
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABbQYK4YKrYb5zHpR_Mot68BzoaIFs0pM',
    appId: '1:855864135025:web:558d65a7563fafecaa3ad0',
    messagingSenderId: '855864135025',
    projectId: 'manga-reader-project-v1',
    authDomain: 'manga-reader-project-v1.firebaseapp.com',
    storageBucket: 'manga-reader-project-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSWBE4f5PD5zcGYhVsF3eEmBB3fQ0IcKU',
    appId: '1:855864135025:android:c0293f5c72964fceaa3ad0',
    messagingSenderId: '855864135025',
    projectId: 'manga-reader-project-v1',
    storageBucket: 'manga-reader-project-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiCZ8umKj8PN4uFawyPbGKa9M8Cdk50nc',
    appId: '1:855864135025:ios:27bf3329b8b22bc8aa3ad0',
    messagingSenderId: '855864135025',
    projectId: 'manga-reader-project-v1',
    storageBucket: 'manga-reader-project-v1.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );
}
